"""Added categories, changed the structure of some tables

Revision ID: 055a55b2322a
Revises: a9c4c84d5be6
Create Date: 2022-03-07 16:47:46.226821

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '055a55b2322a'
down_revision = 'a9c4c84d5be6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
