"""Name to title

Revision ID: 1c06259f16bd
Revises: 4bb116eff052
Create Date: 2022-03-12 16:39:18.228763

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1c06259f16bd'
down_revision = '4bb116eff052'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('menu_items', sa.Column('title', sa.String(), nullable=True))
    op.drop_column('menu_items', 'title')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('menu_items', sa.Column('title', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('menu_items', 'title')
    # ### end Alembic commands ###
