"""Bug fix

Revision ID: 2cf735d69a7f
Revises: 055a55b2322a
Create Date: 2022-03-07 17:03:23.480101

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2cf735d69a7f'
down_revision = '055a55b2322a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
