"""v1

Revision ID: 3f61fc162b2a
Revises: 
Create Date: 2022-03-07 17:41:55.448626

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3f61fc162b2a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('categories')
    op.drop_constraint('menu_items_category_id_fkey', 'menu_items', type_='foreignkey')
    op.drop_column('menu_items', 'category_id')
    op.add_column('menus', sa.Column('restaurant_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'menus', 'restaurants', ['restaurant_id'], ['id'])
    op.drop_column('order_items', 'count')
    op.add_column('restaurant_places', sa.Column('latitude', sa.Float(), nullable=True))
    op.add_column('restaurant_places', sa.Column('longitude', sa.Float(), nullable=True))
    op.drop_index('ix_restaurants_title', table_name='restaurants')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_restaurants_title', 'restaurants', ['title'], unique=False)
    op.drop_column('restaurant_places', 'longitude')
    op.drop_column('restaurant_places', 'latitude')
    op.add_column('order_items', sa.Column('count', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'menus', type_='foreignkey')
    op.drop_column('menus', 'restaurant_id')
    op.add_column('menu_items', sa.Column('category_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('menu_items_category_id_fkey', 'menu_items', 'categories', ['category_id'], ['id'])
    op.create_table('categories',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('title', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('menu_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['menu_id'], ['menus.id'], name='categories_menu_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='categories_pkey')
    )
    # ### end Alembic commands ###
