"""v1

Revision ID: 4bb116eff052
Revises: c18a51d21d2f
Create Date: 2022-03-11 18:02:42.483485

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4bb116eff052'
down_revision = 'c18a51d21d2f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('menu_items', sa.Column('item_image', sa.String(), nullable=True))
    op.drop_column('menu_items', 'profile_image')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('menu_items', sa.Column('profile_image', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('menu_items', 'item_image')
    # ### end Alembic commands ###
