"""restaurant find type changed

Revision ID: 520172479397
Revises: b289901fba24
Create Date: 2022-03-05 23:57:00.252745

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '520172479397'
down_revision = 'b289901fba24'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('restaurant_places', 'longitude')
    op.drop_column('restaurant_places', 'latitude')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('restaurant_places', sa.Column('latitude', sa.FLOAT(), nullable=True))
    op.add_column('restaurant_places', sa.Column('longitude', sa.FLOAT(), nullable=True))
    # ### end Alembic commands ###
