"""upgrade bd

Revision ID: 90edc5ca5ba3
Revises: 520172479397
Create Date: 2022-03-06 17:45:21.557130

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '90edc5ca5ba3'
down_revision = '520172479397'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('restaurant_places', sa.Column('latitude', sa.Float(), nullable=True))
    op.add_column('restaurant_places', sa.Column('longitude', sa.Float(), nullable=True))
    op.add_column('restaurants', sa.Column('login', sa.String(), nullable=True))
    op.drop_index('ix_restaurants_login', table_name='restaurants')
    op.create_index(op.f('ix_restaurants_login'), 'restaurants', ['login'], unique=False)
    op.drop_column('restaurants', 'register')
    op.add_column('users', sa.Column('login', sa.String(), nullable=True))
    op.drop_index('ix_users_login', table_name='users')
    op.create_index(op.f('ix_users_login'), 'users', ['login'], unique=False)
    op.drop_column('users', 'register')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('register', sa.VARCHAR(), nullable=True))
    op.drop_index(op.f('ix_users_login'), table_name='users')
    op.create_index('ix_users_login', 'users', ['register'], unique=False)
    op.drop_column('users', 'login')
    op.add_column('restaurants', sa.Column('register', sa.VARCHAR(), nullable=True))
    op.drop_index(op.f('ix_restaurants_login'), table_name='restaurants')
    op.create_index('ix_restaurants_login', 'restaurants', ['register'], unique=False)
    op.drop_column('restaurants', 'login')
    op.drop_column('restaurant_places', 'longitude')
    op.drop_column('restaurant_places', 'latitude')
    # ### end Alembic commands ###
