"""name to title

Revision ID: a6f18077351d
Revises: c0234ecb1899
Create Date: 2022-03-12 23:16:18.534926

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a6f18077351d'
down_revision = 'c0234ecb1899'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('restaurant_places', sa.Column('title', sa.String(), nullable=True))
    op.drop_column('restaurant_places', 'name')
    op.drop_column('restaurants', 'profile_image')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('restaurant_places', sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('restaurant_places', 'title')
    # ### end Alembic commands ###
