"""v1

Revision ID: a9c4c84d5be6
Revises: 
Create Date: 2022-03-06 20:07:34.758363

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a9c4c84d5be6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('menus', sa.Column('restaurant_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'menus', 'restaurants', ['restaurant_id'], ['id'])
    op.add_column('restaurant_places', sa.Column('latitude', sa.Float(), nullable=True))
    op.add_column('restaurant_places', sa.Column('longitude', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('restaurant_places', 'longitude')
    op.drop_column('restaurant_places', 'latitude')
    op.drop_constraint(None, 'menus', type_='foreignkey')
    op.drop_column('menus', 'restaurant_id')
    # ### end Alembic commands ###
